services:
  - type: web
    name: music-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py & python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
